from app.models import db, Comment



def seed_comments():
    comment1 = Comment(comment='What the dog doin' , user_id=5 , post_id=1)
    comment2 = Comment(comment='Das a cute dog' , user_id=2 , post_id=1)
    comment3 = Comment(comment="Don't get stuck 10" , user_id=5 , post_id=2)
    comment4 = Comment(comment='Cute!' , user_id=3 , post_id=4)
    comment5 = Comment(comment='Awesome view' , user_id=3 , post_id=5)
    comment6 = Comment(comment='ADORABLE', user_id=8, post_id=4)
    comment7 = Comment(comment='As above so below', user_id=5, post_id=3)
    comment8 = Comment(comment="I'm not a party animal, but I do like animal parties.", user_id=10, post_id=5)
    comment9 = Comment(comment='', user_id=3, post_id=6)
    comment10 = Comment(comment='burrito cat', user_id=4, post_id=6)
    comment11 = Comment(comment='Flappy arm man', user_id=1, post_id=7)
    comment12 = Comment(comment='Same', user_id=6, post_id=9)
    comment13 = Comment(comment='amazing!', user_id=7, post_id=10)
    comment14 = Comment(comment=':D' , user_id=5 , post_id=8)
    comment15 = Comment(comment='She wanted to be rescued, but only if it was Tuesday and raining.', user_id=9 , post_id=11)
    comment16 = Comment(comment='That was how he came to win $1 million.', user_id=10 , post_id=17)
    comment17 = Comment(comment='It was a slippery slope and he was willing to slide all the way to the deepest depths.', user_id=5 , post_id=18)
    comment18 = Comment(comment="It turns out you don't need all that stuff you insisted you did.", user_id=7 , post_id=19)
    comment19 = Comment(comment='Random words in front of other random words create a random sentence.', user_id=9 , post_id=20)
    comment20 = Comment(comment='I like this', user_id=3 , post_id=21)
    comment21 = Comment(comment='I like this', user_id=2 , post_id=22)
    comment22 = Comment(comment="There's no reason a hula hoop can't also be a circus ring.", user_id=7 , post_id=3)
    comment23 = Comment(comment="Jason didn't understand why his parents wouldn't let him sell his little sister at the garage sale.", user_id=9 , post_id=4)
    comment24 = Comment(comment='Flying fish flew by the space station.', user_id=10 , post_id=5)
    comment25 = Comment(comment="Don't piss in my garden and tell me you're trying to help my plants grow.", user_id=4 , post_id=6)
    comment26 = Comment(comment='I like this', user_id=4 , post_id=7)


    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)

    db.session.commit()

def undo_comments():
  db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
  db.session.commit()
