from app.models import db, Photos


def seed_photos():
  photo1 = Photos(photo='https://i.imgur.com/KnJ1rsA.png', post_id=1)
  photo2 = Photos(photo='https://i.imgur.com/T9puXgo.png', post_id=3)
  photo3 = Photos(photo='https://i.imgur.com/rV3udFW.png', post_id=5)
  photo4 = Photos(photo='https://i.imgur.com/GqFnR45.png', post_id=2)
  photo5 = Photos(photo='https://i.imgur.com/J87Uthp.png', post_id=10)
  photo6 = Photos(photo='https://i.imgur.com/GSMAorY.png', post_id=17)
  photo7 = Photos(photo='https://i.gyazo.com/b06ceb94fef2262d08f41be3a7c1009e.png', post_id=20)
  photo8 = Photos(photo='https://i.imgur.com/fGk4iGe.jpg', post_id=13)
  photo9 = Photos(photo='https://i.imgur.com/98LG7cS.jpg', post_id=16)
  photo10 = Photos(photo='https://i.imgur.com/eNwuuEb.png', post_id=18)
  photo11 = Photos(photo='https://i.imgur.com/0XfbydJ.jpg', post_id=4)
  photo12 = Photos(photo='https://i.imgur.com/NLCNw9R.jpg', post_id=19)
  photo13 = Photos(photo='https://i.imgur.com/PP43AuO.jpg', post_id=11)
  photo14 = Photos(photo='https://i.imgur.com/dPnFEHQ.png', post_id=22)
  photo15 = Photos(photo='https://i.imgur.com/pzrYK49.jpg', post_id=6)
  photo16 = Photos(photo='https://i.imgur.com/20dojMh.jpg', post_id=14)
  photo17 = Photos(photo='https://i.imgur.com/GvYJHGo.jpg', post_id=21)
  photo18 = Photos(photo='https://i.imgur.com/Vk22MN4.jpg', post_id=12)
  photo19 = Photos(photo='https://i.imgur.com/KrwtoLZ.jpg', post_id=23)
  photo20 = Photos(photo='https://i.imgur.com/yQTHCE8.jpg', post_id=15)
  photo21 = Photos(photo='https://i.gyazo.com/869923e006ed7f36b6515837f6b650d0.jpg', post_id=24)
  photo22 = Photos(photo='https://i.gyazo.com/3c07d1b0f164d92b2e3a6246c71cdf4f.jpg', post_id=25)
  photo23 = Photos(photo='https://i.imgur.com/Q0Te7at.png', post_id=7)
  photo24 = Photos(photo='https://i.imgur.com/PIQScOR.jpg', post_id=8)
  photo25 = Photos(photo='https://i.imgur.com/YH94SLo.png', post_id=9)

  db.session.add(photo1)
  db.session.add(photo2)
  db.session.add(photo3)
  db.session.add(photo4)
  db.session.add(photo5)
  db.session.add(photo6)
  db.session.add(photo7)
  db.session.add(photo8)
  db.session.add(photo9)
  db.session.add(photo10)
  db.session.add(photo11)
  db.session.add(photo12)
  db.session.add(photo13)
  db.session.add(photo14)
  db.session.add(photo15)
  db.session.add(photo16)
  db.session.add(photo17)
  db.session.add(photo18)
  db.session.add(photo19)
  db.session.add(photo20)
  db.session.add(photo21)
  db.session.add(photo22)
  db.session.add(photo23)
  db.session.add(photo24)
  db.session.add(photo25)
  db.session.commit()

def undo_photos():
  db.session.execute('TRUNCATE photos RESTART IDENTITY CASCADE;')
  db.session.commit()
